config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Other routes...

  get '/', to: 'users#index'
  get "/users", to: "users#index"
  get "/users/:id", to: "users#show"
  get "/users/:id/posts", to: "posts#index"
  get "/users/:id/posts/:post_id", to: "posts#show"
  get '/posts/new', to: 'posts#new'
 # config/routes.rb
resources :posts do
  resources :comments, only: [:new, :create]
  post 'likes', to: 'likes#create'
end

  
end

app/models/ability.rb
class Ability
    include CanCan::Ability
  
    def initialize(user)
      user ||= User.new # Guest user
  
      if user.role == 'admin'
        can :manage, :all # Admin can manage all
      else
        can :delete, Post, user_id: user.id
        can :delete, Comment, user_id: user.id
      end
    end
  end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comment_counter

  private

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_like_counter

  private

  def update_like_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_save :update_post_counters

  def five_recent_comments
    Comment.where(post_id: id).order(created_at: :desc).limit(5)
  end

  private

  def update_post_counters
    user.update(posts_counter: user.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments
  has_many :likes
  has_many :posts, class_name: 'Post', foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }

  after_initialize :set_defaults

  def set_defaults
    self.posts_counter = [posts.count, 0].max
  end

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = 'Comment created successfully.'
    else
      flash[:error] = 'Error: Comment could not be created'
    end
    redirect_to post_path(@post)
  end

  def destroy
    authorize! :delete, @comment
    post = @comment.post # Assuming the comment belongs to a post
    @comment.destroy
    redirect_to user_post_path(post.user, post), notice: 'Comment was successfully deleted.'
  end  

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
# app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    like = Like.new(user: current_user, post: @post)
    if @post.likes.find_by(user_id: current_user.id)
      flash[:notice] = 'You already liked this post'
    elsif like.save
      flash[:success] = 'You liked this post'
    end
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(posts: :comments).find(params[:id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    return unless @post.save

    redirect_to post_path
    render 'new'
  end

  private

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'users'
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Publisher</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>My Blog App</title>
    <meta charset='utf-8' />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'style' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_comment.html.erb
<div class='comment'>
  <h2><%= comment.user.name %>: </h2>
  <p><%= comment.text %></p>
</div>

app/views/partials/_post.html.erb
<div class='post-body'>
  <div class='post-header'>
    <h2><%= "#{post.title} by #{post.user.name}" %></h2>
  </div>
  <p class='post-text'>
    <% if short && post.text.split(' ').length > 15 %>
      <%= post.text.split(' ').slice(0,15).join(' ') %>...
    <% else %>
      <%= post.text %>
    <% end %>
  </p>
  <p class='post-counters'>
    <%= "Comments: #{post[:comments_counter]}" %>,
    <%= "Likes: #{post[:likes_counter]}" %>
  </p>
</div>

app/views/partials/_user_card.html.erb
<%= link_to "/users/#{user.id}", class: 'user-nav-link' do %>
    <div class='user-card'>
       <%= image_tag 'https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', class: 'user-photo', alt: 'profile picture' %>
        <div class="user-info">
            <h2><%= user.name %></h2>
            <p>Number of posts: <%= user.posts_counter %></p>
        </div>
    </div>
<% end %>

app/views/posts/index.html.erb
<%= render partial: 'partials/user_card', locals: { user: @user } %>

<% @posts.each do |post| %>
  <div class='post-ctr'>
    <%= render partial: 'partials/post', locals: { post: post, short: true } %>
    <% if post.comments.length > 0 %>
      <div class='comments'>
        <% post.five_recent_comments.each do |comment| %>
          <%= render partial: 'partials/comment', locals: { comment: comment } %>
        <% end %>
      </div>
    <% end %>
    <%= link_to "/users/#{@user.id}/posts/#{post.id}" do %>
      <button type='button' class= 'pagination'>See this post</button>
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= form_with scope: :post, url: post_path, method: :post do |form| %>
  <div style="margin-bottom: 15px;">
    <%= form.label :title, "Title", style: "font-weight: bold;" %>
    <%= form.text_field :title, style: "width: 100%; padding: 8px; border-radius: 4px; border: 1px solid #ccc;" %>
  </div>
  
  <div style="margin-bottom: 15px;">
    <%= form.label :text, "Text", style: "font-weight: bold;" %>
    <%= form.text_field :text, style: "width: 100%; height: 100px; padding: 8px; border-radius: 4px; border: 1px solid #ccc;" %>
  </div>
  
  <%= form.submit "Create", style: "background-color: #daad86; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer;" %>
<% end %>

app/views/posts/show.html.erb
<div class='post-ctr'>
  <%= render partial: 'partials/post', locals: { post: @post, short: false } %>
  <%= button_to "Like", post_likes_path(@post), remote: true %>
  <small><%= flash[:notice] %></small>
  <% if @post.comments.length > 0 %>
    <div class='comments'>
      <% @post.comments.each do |comment| %>
        <%= render partial: 'partials/comment', locals: { comment: comment } %>
        <% if can? :delete, comment %>
          <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <%= form_with model: Comment.new, url: post_path(@post) do |form| %>
    <%= form.text_field :text, placeholder: 'Make a comment' %>
    <%= form.submit "Submit" %>
  <% end %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= render partial: 'partials/user_card', locals: { user: user } %>
<% end %>

app/views/users/show.html.erb
<%= render partial: 'partials/user_card', locals: { user: @user } %>

<div class='bio'>
  <h2>Bio</h2>
  <p><%= @user.bio %></p>
</div>

<div class='feed'>
  <% @user.three_recent_posts.each do |post| %>
    <%= render partial: 'partials/post', locals: { post: post, short: true } %>
  <% end %>
  <% if @user.posts.length > 0 %>
    <%= link_to "/users/#{@user.id}/posts" do %>
      <button type='button' class='see_all'>See all posts</button>
    <% end %>
  <% end %>
</div>